### PR TITLE
add in new RPE 3rd party ack's

### PR DESCRIPTION
**Pull request by benritchie**
Ellie - now BGCF is part of CC, I've moved our third party Ack's across.  can you please review?

### CODE REVIEW

**Comment by benritchie** [comment]
Ellie - are you the right person to review this?

**Comment by benritchie** [comment]
Ping...
This is required for the V11.a release.

**Comment by eleanor-merry** [comment]
Passing to @johadalin

**Comment by johadalin** [comment]
@benritchie These look fine. As you have just put '3-clause-BSD' i'm assuming you've double checked the components were using the exact text of the proper BSD, rather than any modified version?
Also, going forward, i think we may want to include information about what components are using the third party dependencies we include. Are you able to give us any information on that?

**Comment by benritchie** [comment]
I've added that information.  
Yep, its standard BSD
Thanks!

**Pull request merged**
